[package]
name = "eventwork_tcp"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_log = "0.6.0"
bevy_eventwork = {path = "../"}
async-net = "1.6.1"
futures-lite = "1.12.0"
bincode = "*"